name: Deploy playground to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
      - .github/workflows/*.yml
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
      - .github/workflows/*.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm install
      - run: npm run generate
      - run: npm run prestart
      - run: mkdir -p dist && cp -r site/* dist/ || true
      - run: cp tree-sitter-pharo.wasm dist/
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4